apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=background
      - CreateNamespace=true
  source:
    chart: metrics-server
    repoURL: "https://kubernetes-sigs.github.io/metrics-server/"
    targetRevision: 3.8.2
    helm:
      parameters:
        - name: serviceMonitor.enabled
          value: "true"
      values: |
        nodeSelector: {nodegroup-name: node-name}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
